### ISSUE TITLE
Generer une nouvelle commande (cote back - thelia v2.1.2)

### ISSUE THREAD

**Issue by zzuutt** [thelia-modules/OrderCreation#1]
Bonjour,

il y a peut etre un bug au niveau de la gestion des commandes via le back
Si on passe une commande pour un client cote back
Il ne reste qu'un seul produit en stock

![10-03-2015 11-05-10](https://cloud.githubusercontent.com/assets/7439945/6575568/22338588-c730-11e4-8faa-a61bdc923d41.jpg)

le client paie par cheque
lorsque l'on passe la commande en 'paye', on a une erreur stock

![10-03-2015 11-06-15](https://cloud.githubusercontent.com/assets/7439945/6575582/38bd4df2-c730-11e4-9447-adf5255c2f20.jpg)

Apparemment lors de la generation du bon de commande, on deduit du stock et lorsque l'on passe la commande en payee cela re-deduit du stock

Dans l'onglet Livraison et facturation, une date de facturation est affichee
dans la table le champ date pour la facture est vide, vu que la commande n'est pas payee

![10-03-2015 11-16-36](https://cloud.githubusercontent.com/assets/7439945/6575588/451868a2-c730-11e4-8ef6-8884bfcdfc3b.jpg)

**Comment by Yochima** [comment]
Salut,

Je regarde ça ce soir. Merci pour l'info :)

**Comment by Yochima** [comment]
Il semblerait que la creation manuelle de commande impacte TOUJOURS le stock (contrairement aux commandes créées via le Front).

J'ai donc fais une PR pour que la gestion de stock entre une commande manuelle ET une commande via le Front soit identique.

voici le correctif que j'ai suggéré si tu veux corriger en avance dans ton projet :)
https://github.com/Yochima/thelia/commit/93dfd9bfc3bc76f29943f8c7335cef90e72c1777

**Comment by zzuutt** [comment]
Parfait !
pour les nouvelles commandes passees cote back -> OK
pour les anciennes commandes exemple celle citee en plus haut ID 311 cela me deduit du stock lorsqu' on la passe en paye (ce n'est pas grave - je l'annule et la repasse)

Merci !!!

**Comment by Yochima** [comment]
Oui en fait cela vient du numéro de version de tes commandes.
Dès qu'elles possèdent un numéro de version supérieur à 1, tu ne devrais plus avoir de problème.
L'explication se trouve dans la fonction updateQuantity() dans la classe \Thelia\Action\Order.php ^^

**Comment by zzuutt** [comment]
Merci !
:+1:   :beer:
