### ISSUE TITLE
Stock non deduit

### ISSUE THREAD

**Issue by zzuutt** [thelia-modules/OrderCreation#2]
Bonjour,

Maintenant suite a la modif, lorsque l'on passe une commande cote back 
le stock n'est pas deduit au moment ou le bon de commande est genere
(Avec un paiement par cheque - je n'ai pas teste avec un autre)
exemple:
![12-03-2015 13-30-19](https://cloud.githubusercontent.com/assets/7439945/6617831/336313b2-c8bd-11e4-9ecd-3a7317e27e16.jpg)

dans le catalogue, la QT produit est toujours a 14

![12-03-2015 13-31-55](https://cloud.githubusercontent.com/assets/7439945/6617868/806e0edc-c8bd-11e4-885b-8cc9346bffb0.jpg)

Apres avoir passe la commande en 'Payee'

![12-03-2015 13-35-39](https://cloud.githubusercontent.com/assets/7439945/6617863/7284d9c2-c8bd-11e4-977b-0221e5dbc98f.jpg)

le fonctionnement cote Front, on deduit du stock lors de la generation du bon de commande pas au paiement

**Comment by Yochima** [comment]
Salut,

Si tu souhaites que ton stock soit impacté dès la création de la commande, il faut que la fonction manageStockOnCreation de ton module de paiement te retourne VRAI.

Par défaut, celle-ci fait un return "false". Donc actuellement ton stock s'impactera au moment ou tu changeras le statut de ta commande.

(Ce fonctionnement est nouveau depuis la 2.1.1)

**Comment by zzuutt** [comment]
Merci
On peut trouver une liste des changements de fonctionnement quelque part?

**Comment by Yochima** [comment]
Oui bien sûr ! 
juste ici :)
https://github.com/thelia/thelia/blob/master/CHANGELOG.md

**Comment by zzuutt** [comment]
Merci !
